project:
  type: book

book:
  title: "CDRL Kinome Analysis Omnibus"
  author: "Cognitive Disorders Research Lab"
  date: "4/30/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - platform.qmd
    - data_output.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



