project:
  type: book

book:
  title: "CDRL Kinome Analysis Omnibus"
  author: "Cognitive Disorders Research Lab"
  date: "4/30/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - platform.qmd
    - data_generation.qmd
    - analytical_approaches.qmd
    - upstream_kinase.qmd
    - kinase_pathways.qmd
    - kinase_visualization.qmd
    - case_study.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-annotations: select
  pdf:
    documentclass: scrreprt



